# Generated by Django 2.1.3 on 2018-11-15 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='owner',
        ),
    ]
